server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:verify
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
#  cron:
#    scheluded: * 1 1 ? * TUE
#    zone: America/Sao_Paulo